openapi: 3.0.0
info:
  title: Task Management API
  version: 1.0.0
  description: API para gerenciamento de tarefas

paths:
  /tasks:
    post:
      summary: Criar uma nova tarefa
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TaskCreate'
      responses:
        '200':
          description: Tarefa criada com sucesso
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'
    get:
      summary: Listar todas as tarefas
      responses:
        '200':
          description: Lista de tarefas
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Task'

  /tasks/{task_id}:
    get:
      summary: Obter detalhes de uma tarefa
      parameters:
        - in: path
          name: task_id
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Detalhes da tarefa
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'
        '404':
          description: Tarefa não encontrada
    put:
      summary: Atualizar uma tarefa
      parameters:
        - in: path
          name: task_id
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TaskUpdate'
      responses:
        '200':
          description: Tarefa atualizada com sucesso
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'
        '404':
          description: Tarefa não encontrada
    delete:
      summary: Deletar uma tarefa
      parameters:
        - in: path
          name: task_id
          required: true
          schema:
            type: integer
      responses:
        '204':
          description: Tarefa deletada com sucesso
        '404':
          description: Tarefa não encontrada

components:
  schemas:
    Task:
      type: object
      properties:
        id:
          type: integer
        title:
          type: string
        description:
          type: string
        status:
          type: string
        created_at:
          type: string
          format: date-time

    TaskCreate:
      type: object
      properties:
        title:
          type: string
        description:
          type: string
        status:
          type: string

    TaskUpdate:
      type: object
      properties:
        title:
          type: string
        description:
          type: string
        status:
          type: string